### ISSUE TITLE
Collection of Notion Apps and Libraries

### ISSUE THREAD

**Issue by MaaxGr** [samuelkraft/notion-blog-nextjs#1]
Hey Samuel,

wow. Amazing project! 

i have started to create a open source project that lists open source projects around the new notion api.
https://github.com/MaaxGr/open-source-notionapi-apps

I have added your Next.JS Blog App to the integration list. Is that okay for you?

Keep going on the amazing work! :)

Kind Regards
Max

**Comment by samuelkraft** [comment]
Great, thanks! :)
