### ISSUE TITLE
Example Notion Page

### ISSUE THREAD

**Issue by iqlal** [samuelkraft/notion-blog-nextjs#10]
Hey Samuel can you give me link to your notion base ?

**Comment by samuelkraft** [comment]
Hi! Here's the table used https://www.notion.so/5b53abc87b284beab0c169c9fb695b4d?v=e4ed5b1a8f2e4e12b6d1ef68fa66e518

**Comment by Just-Moh-it** [comment]
It would be great to have this in the README, got me 5 minutes to find the solution, was getting errors while parsing data on the application, though had followed each step.

**Comment by iqlal** [comment]
> 

Just add the link and pull request to the README file 😊

**Comment by samuelkraft** [comment]
Added this to the readme, thanks!
