### ISSUE TITLE
Trouble on Notion Hosted Image

### ISSUE THREAD

**Issue by IamMrandrew** [samuelkraft/notion-blog-nextjs#13]
Love the Notion API as you do! Currently discovering using the Notion API as a CMS. Love the way you process with the blocks and I might take urs as reference especially for the in-text styling/ annotation.

I have a similar approach as you do for the image. Grabbing the url of the image block (which is hosted on s3 by notion) and display it.

# Problem
However, I discover that the image sometimes is not loaded on first launch of the page. A refresh is required to load the image. And after that, it is fine for a while even I close it and reopen on new tab or another device. (Like a warmup for waking the image)

I see that your example website have similar issue and I am wondering if you have any clue about it.

I am using vercel for hosting as well.

## Demo
First launch of my website powered by Notion API
![image](https://user-images.githubusercontent.com/62586450/137904240-25e15599-cf80-4d1e-9ce1-5a9d5c08ac2d.png)

After a refresh
![image](https://user-images.githubusercontent.com/62586450/137904313-5aef6472-8eef-4b31-ad5e-65c948cc444c.png)u

**Comment by dwisk** [comment]
I'd like to share an idea I'm testing, by using the client to trigger a data-reload:

- Writing prop "lastFetch" in `lib/notion.js → getPage` into page data (to have it cached as well)
```
export const getPage = async (pageId) => {
  const response = await notion.pages.retrieve({ page_id: pageId });
  response.lastFetch = new Date().getTime();
  return response;
};
```

- Calculate Age in `pages/[id].js` and use router to force data refresh in `[id].js` if older than 1 hour
```
  import { useRouter } from "next/dist/client/router";
  …
  const cacheAge = Math.floor((new Date() - new Date(page.lastFetch)) / 1000) ;
  const router = useRouter();
  if (cacheAge > 3600)  router.replace(router.asPath);
```

**Comment by dwisk** [comment]
So far, it looks good! At least I got no complaints anymore, but also I pushed a lot of updates the last two days, which invalidated the cached content, too. My feeling is, it is working.

**Comment by IamMrandrew** [comment]
@dwisk Hey there after few months😂 Wondering how `router.replace(router.asPath)` trigger a data refresh? 

I have tried this method and it appears to be the most straightforward but hacky solution to refresh ISR content changes or Notion's short-life image url. However, `router.replace()` did not trigger to get the new staticProps. `router.reload()` does work but definitely not what we want.

Any new clues or new solution?

**Comment by IamMrandrew** [comment]
@dwisk Just read your repository, do I have to combine the new on-demand ISR revalidate api to do so?
