### ISSUE TITLE
Image render does not support caption

### ISSUE THREAD

**Issue by ggiande** [samuelkraft/notion-blog-nextjs#20]
There is currently breaking code where caption is declared and fetched by the API. It appears that Notion may have discontinued support for captions under images or are yet to include it.
[Notion API - Image Blocks](https://developers.notion.com/reference/block#image-blocks) Further down, captions are used for File Blocks and Bookmark Blocks.

I suggest commenting out/removing the use of captions within the Image block. Let me know if you would like me to contribute.

**Comment by samuelkraft** [comment]
Hi! Where is the crash occurring for you? Captions are working for me:

<img width="500" alt="Screenshot 2022-01-21 at 09 57 10" src="https://user-images.githubusercontent.com/2223418/150497289-9b594274-a24c-4898-89e0-b89ea499130d.png">

**Comment by ggiande** [comment]
Hmm, I am not sure which code block you are rendering. 
```js
    case "image":
      const src =
        value.type === "external" ? value.external.url : value.file.url;
        const caption = value.caption ? value.caption[0].plain_text : "";
      return (
        <figure>
          <img src={src} alt={caption} />
          {caption && <figcaption>{caption}</figcaption>}
        </figure>
```
When the code block to render is an image, the caption crashes with the following error.
![image](https://user-images.githubusercontent.com/44848977/150657065-8ac5bdf2-863d-4bdf-a581-b9a414f2bf31.png)

**Comment by samuelkraft** [comment]
Pushed a fix, can you verify? https://github.com/samuelkraft/notion-blog-nextjs/commit/acacfe4b766ae776cfca2e1133b775120b7569d9

**Comment by ggiande** [comment]
@samuelkraft Fix works!
I've tried researching how to address nulls and undefined and I guess it didn't click. Think there's a reason why [Image Blocks - Notion](https://developers.notion.com/reference/block#image-blocks) doesn't show captions? Are captions allowed for all objects?

**Comment by samuelkraft** [comment]
Great! I think the docs are just a bit confusing, the image is a file object and the [file block docs](https://developers.notion.com/reference/block#file-blocks) shows the caption
