### ISSUE TITLE
Support the file_block type

### ISSUE THREAD

**Issue by ggiande** [samuelkraft/notion-blog-nextjs#23]
The Notion API now supports file blocks. To enable users to use this block without the need to download the files locally, we can use the external file path to redirect users to the site, much like notion already does so. A future feature could be to add a download button that makes a request to AWS to locally download the file from the servers.

**Comment by DefCon-007** [comment]
@ggiande @samuelkraft This works great, but I saw that the URLs returned by Notion API are valid only for 1 hour and since the data is cached during build in getStaticProps, won't that be a issue?
