### ISSUE TITLE
invalid_request_url

### ISSUE THREAD

**Issue by nagysandorantal** [samuelkraft/notion-blog-nextjs#25]
Hi,

Your Notion integration example looks promising. Thanks for repo!
Following the tutorial I created a token, a list page, have DB ID as well. given rights to integration.

It fails to display notion content:

NOTION_TOKEN=secret_WOruO6LgJxjahR4O0gxRWP9BR4hxVwFQPZhqI****
NOTION_DATABASE_ID=fc3b5855162b443faff8c016cf****

**Node terminal**
@notionhq/client warn: request fail { code: 'invalid_request_url', message: 'Invalid request URL.' }
error - APIResponseError: Invalid request URL.

**Browser console error:**

index.js?46cb:323 
Uncaught     at buildRequestError (file:///Users/nagysandorantal/Code/nextJs/solidCode-site/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (file:///Users/nagysandorantal/Code/nextJs/solidCode-site/node_modules/@notionhq/client/build/src/Client.js:304:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getDatabase (webpack-internal:///./lib/notion.js:14:22)
    at async getStaticProps (webpack-internal:///./pages/index.js:295:22) .....

**Comment by samuelkraft** [comment]
Hi, I would try removing node modules and reinstalling all dependencies. Also make sure the environment variables are in a file called `.env.local` and check that the database id is correct.
If that's not working then open a ticket in the notion sdk repo https://github.com/makenotion/notion-sdk-js

**Comment by nagysandorantal** [comment]
I have done those steps before raising the issue. Not quite sure how your example website functions then?
Probably you are using a different notion sdk version??

env.local - OK
node modules reinstall - Done
Checked BD IDs, URL is formed slightly differently compared to the one in their tutorial:
"https://www.notion.so/**fc3b5855162b443faff8c016cfed7a54**?v=24ccee9a3f774d608be3cd68356775e2"
Not sure how to verify, so raise a bug with them.

Thanks!
