### ISSUE TITLE
Slug endpoint instead of id

### ISSUE THREAD

**Issue by cengizcmataraci** [samuelkraft/notion-blog-nextjs#26]
Hello Samuel,

Thank you very much for this good example, I am developing a site based on your example, but I want to make the endpoints of blog posts slug instead of id, for this, when I use the slugify library and implement it as follows, APIResponseError: path failed validation: path.page_id should be a valid uuid error is coming.

index.js
![image](https://user-images.githubusercontent.com/13690848/151438059-07f1f65d-c546-4e33-8554-f9668ef3085a.png)

[slug].js
![image](https://user-images.githubusercontent.com/13690848/151438159-1eea518c-14c4-4adc-8fa9-29e85b796e51.png)

The remaining codes are as you did. How do I get rid of this error? Since I'm just starting out, I can't make sense of it and I couldn't find almost any resources on this subject. You are my only hope. :D

**Comment by cengizcmataraci** [comment]
I forgot the notion page, so sorry.

notion.js
![image](https://user-images.githubusercontent.com/13690848/151438918-8d71cc8d-4d2a-425e-b316-8a955c6f7e5e.png)

**Comment by samuelkraft** [comment]
Hi! The API still expects a page id, you cannot query on the slug. In `getStaticProps` in `[slug].js` you need to figure out the page id based on the slug. You can do that by first fetching the database (`const database = await getDatabase(databaseId);`), and then filtering the results based on the page slug. 

I did something similar in [my old blogpost](https://samuelkraft.com/blog/personal-website-with-next-and-notion) before the official API was out but the logic is the same:
```
export const getStaticProps: GetStaticProps = async context => {
    const bookRes = await fetch(https://notion-api.splitbee.io/v1/table/[NOTION_TABLE_ID])
    const bookData = await bookRes.json()

    if (!bookData) {
        return {
            notFound: true,
        }
    }

    const { slug } = context.params
    const book = bookData.find(b => slugify(b.name, { lower: true }) === slug)

    const pageRes = await fetch(`https://notion-api.splitbee.io/v1/page/${book.id}
    const pageData = await pageRes.json()

      return {
        props: {
          book,
          page: pageData,
        },
        revalidate: 1,
      }
    }
```

You can also take a look at [this course](https://egghead.io/lessons/next-js-use-slugified-titles-for-url-in-next-js-with-the-notion-api), I haven't watched it but looks like it does the same thing but with the official API [here](https://github.com/dijonmusters/notion-api-egghead-course/blob/master/04-slugify-page-data/pages/recipes/%5Bslug%5D.js#L45).

**Comment by cengizcmataraci** [comment]
Thank you for answer @samuelkraft , but when I implement this I get this error: A required parameter (slug) was not provided as a string in getStaticPaths for /blog/[slug].
This is before:
![image](https://user-images.githubusercontent.com/13690848/151819866-cb5da9b1-2b6f-4cff-9bb2-36a14c8cd049.png)
And this is after:
![image](https://user-images.githubusercontent.com/13690848/151820675-07ca9dd1-3754-46b2-a194-ca41cd716bbf.png)
But when I do that, I get 404 error. I don't really catch the solution. What do you suggest I do?
