### ISSUE TITLE
Blog Post uses Different ENV Variable

### ISSUE THREAD

**Issue by Christopher-Hayes** [samuelkraft/notion-blog-nextjs#27]
The blog post that goes with this repo mentions using the env variable `NOTION_TABLE_ID` when the code only seems to reference `NOTION_DATABASE_ID`. The post didn't have a comment section, so leaving this here.

Blog link: https://samuelkraft.com/blog/building-a-notion-blog-with-public-api
![image](https://user-images.githubusercontent.com/6013871/151736623-28ce7aee-9388-4a15-a2fd-d313630e86cb.png)

Thanks for the guide + source code, btw.

**Comment by samuelkraft** [comment]
Thanks for letting me know, fixed now!
