### ISSUE TITLE
Code blocks not syntax highlighting 

### ISSUE THREAD

**Issue by jlokos** [samuelkraft/notion-blog-nextjs#28]
Is there any way to make code blocks have syntax highlighting?

**Comment by samuelkraft** [comment]
Sure you can use something like [React Syntax Highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) or [React Prism](https://github.com/FormidableLabs/prism-react-renderer). Check out the example from react-syntax-highlighter below and feel free to open a PR if you implement it!

```
import SyntaxHighlighter from 'react-syntax-highlighter';
import { docco } from 'react-syntax-highlighter/dist/esm/styles/hljs';
const CodeBlock = () => {
  const codeString = '(num) => num + 1';
  return (
    <SyntaxHighlighter language="javascript" style={docco}>
      {codeString}
    </SyntaxHighlighter>
  );
};
```
