### ISSUE TITLE
Error in reading title

### ISSUE THREAD

**Issue by okandavut** [samuelkraft/notion-blog-nextjs#3]
Hi, 
First of all thanks for the project. I tried with my database. I got an error. Do you have an idea about this?

My object is like this : 
![image](https://user-images.githubusercontent.com/10600157/118377754-f781b100-b5d7-11eb-9887-d818a9d7f88c.png)

![image](https://user-images.githubusercontent.com/10600157/118377727-b5586f80-b5d7-11eb-8416-b78fa4f37191.png)

**Comment by samuelkraft** [comment]
Hi! 
It looks like there's an issue with your Name object. If I create a new table or list in Notion the Name object is just `Name` without quotes. Make sure that it's named exactly that or edit the line to match your case: 
`{post.properties["Name"].title[0]?.plain_text}`

**Comment by okandavut** [comment]
Hi, i checked it but i couldn't find on Notion notebook where can I change the property "Name" to name without quotes. Sorry for taking your time.

**Comment by okandavut** [comment]
Solved problem on Notion properties thanks for your help @samuelkraft
