### ISSUE TITLE
Missing Cover images for posts 

### ISSUE THREAD

**Issue by hellostanley** [samuelkraft/notion-blog-nextjs#36]
_(First thanks for sharing this starter kit)_

Struggling to add a cover image to the blog posts, either in the index or [slug].js file. 
Where would you call this from in your template? I have tried several methods but found only errors.

Appreciate any help here.

**Comment by capitanbarbosa** [comment]
Ditto bruh. thanks OG. 

I'm trying as well and using a DB and post urls to map on a separate page.

**Comment by samuelkraft** [comment]
Did you check the response for the `page` or `database` object as outlined in [this changelog](https://developers.notion.com/changelog/page-icons-cover-images-new-block-types-and-improved-page-file-properties)?
