### ISSUE TITLE
API token is invalid.

### ISSUE THREAD

**Issue by kamilklkn** [samuelkraft/notion-blog-nextjs#6]
Hi,
First of all thanks for the project. I tried with my database. 

I take the database id and write it instead. Does it mean "NOTION_TOKEN" from API tokon in this error?

If so, where exactly should I access the "NOTION_TOKEN" value? Because when I tried it with "Internal Integration Token" value, it didn't work either.

<img width="984" alt="Ekran Resmi 2021-05-19 01 44 31" src="https://user-images.githubusercontent.com/5111512/118733501-0faa3800-b845-11eb-883a-1d0dd283037c.png">

**Comment by Dipeshwagle** [comment]
"NOTION_TOKEN" is the Internal Integration Token itself, I suspect some kind of error accessing the token. Can you log the  "NOTION_TOKEN" and check if it's present.

**Comment by samuelkraft** [comment]
Make sure you are using the correct token (it should start with `secret_`) and that it's added it to a file called `.env.local` in the root of your project. 
You can try adding the tokens to the `.env.example` file and rename it if you're having issues.

**Comment by kamilklkn** [comment]
It was fixed when I deleted the project and reinstalled all the packages. Thanks for your help.

**Comment by jeffersonvasconcellos** [comment]
Mesmo seguindo os passos, não consigo solucionar esse problema.
Aqui mostra erro no Token, e as vezes é no ID.

![erro_code](https://user-images.githubusercontent.com/104874696/188223707-3de8ec47-5ca2-4e75-a856-cd34eecf5651.png)

**Comment by wavinginspace** [comment]
changing the `.env.local` to just `.env` fixed it for me.

**Comment by iankilmister** [comment]
> Make sure you are using the correct token (it should start with `secret_`) and that it's added it to a file called `.env.local` in the root of your project. You can try adding the tokens to the `.env.example` file and rename it if you're having issues.



> It was fixed when I deleted the project and reinstalled all the packages. Thanks for your help.

@kamilklkn could you confirm to me a few things?
1) is the token a 156 characters value?
2) did you use "secret_" before the token value retrieved from the application cookie (i.e. "secret_1234567890...")
3) did you use the file name as "`env.local` or `env.` ?
Thanks in advance!

**Comment by iankilmister** [comment]
Thanks, Samuel, it worked! Have a great day!

Cassiano Gobbet | Founder | Journalist | PM
***@***.*** ***@***.***>
 troovr.com <https://troovr.com/>
 <https://www.twitter.com/cassianogobbet>  <https://www.linkedin.com/in/cassianogobbet>  <https://us04web.zoom.us/j/7898089816?pwd=RXZScGNEU1ZiQlVValNRdGJnbFd1dz09>  <https://telegram.me/cassiano_fr>

**Comment by iankilmister** [comment]
Samuel, hello again. I have another question:

On the table, onde of the fields we would fill are the “slug” and “tags". How should I do to have the slug implemented in the URL? The tags, I presume, are harvested by the Google bots, but I can’t figure out how to use the slug. 

I saw this piece in your explanation of the Readme:

"We're using the post id as slug for sake of simplicity in this tutorial. For SEO purposes it would be better to use a prettier slug based on the title. You can do this by either manually adding a slug property to each post in Notion or generating a slug with a package like slugify”.

Although I have been filling the slug property, the URLs at Vercel are still random. Is there a tutorial you can point me to so I can prettify the slugs?

Thanks a lot and have a nice day!

Cassiano Gobbet | Founder | Journalist | PM
***@***.*** ***@***.***>
 troovr.com <https://troovr.com/>
 <https://www.twitter.com/cassianogobbet>  <https://www.linkedin.com/in/cassianogobbet>  <https://us04web.zoom.us/j/7898089816?pwd=RXZScGNEU1ZiQlVValNRdGJnbFd1dz09>  <https://telegram.me/cassiano_fr>

**Comment by samuelkraft** [comment]
> Is there a tutorial you can point me to so I can prettify the slugs?

@iankilmister You have to edit the data fetching functions to query for the slug instead of id. Here's a post from another blog giving some guidance: https://www.coryetzkorn.com/blog/how-the-notion-api-powers-my-blog
